name: Build

on: push

jobs:
  build:
    runs-on: windows-2022

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Build
        run: ./build.ps1 64 d3d9 your.dll
        # TODO: version d3d9 d3d10 d3d11

      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          path: ./build/Release/*.dll
