name: Build

on: push

jobs:
  build:
    runs-on: windows-2022

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Build
        run: ./build.ps1 64 version b3hm.dll

      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          path: ./build/Release/*.dll
