name: Build

on: push

jobs:
  build:
    runs-on: windows-2025

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: gendef
        shell: bash
        run: ./gendef.sh version

      - name: Build
        run: |
          cmake -G "Visual Studio 17 2022" -A "x64" -B "./build" -DMODULE="version" -DDLL_LOAD="b3hm.dll"
          cmake --build ./build --config Release

      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          path: ./build/Release/*.dll
